<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link rel="stylesheet" href="style/main3.css" />
		<title>Редактирование таблицы на Python, JavaScript</title>
		<meta name="ROBOTS" content="NOINDEX,NOFOLLOW,NOARCHIVE" />
        <link rel="shortcut icon" href="image/favicon.ico" type="image/x-icon" />
	</head>
<body>
	<div class="center">

<h1><a href=".">Редактирование таблицы на Python, JavaScript (на основе HTML 5, CSS 3.0)</a></h1>